Add JSON formatting to DataServlet and json parsing to JS file
alexcn3/step-portfolio pull request #9
Opened 2020-06-02 21:11 UTC by alexcn3

![Screenshot 2020-06-02 at 5 07 22 PM](https://user-images.githubusercontent.com/47462684/83570489-23557500-a4f4-11ea-92a3-50cb598b8932.png)

2020-06-02 22:33 UTC, eyh8 requested changes

2020-06-02 22:33 UTC, eyh8 commented on portfolio/src/main/webapp/script.js
> +//   for (Array i : greeting) {
Wanna get rid of the comments and console logs?

2020-06-02 22:33 UTC, eyh8 commented on portfolio/src/main/webapp/script.js
> +  for (i = 0; i < greeting.length; i++) {
`for (let i = 0; i < greeting.length; i++)`

2020-06-02 22:33 UTC, eyh8 commented on portfolio/src/main/webapp/script.js
> +  for (i = 0; i < greeting.length; i++) {
Let me know if you need an explanation of why this is better 😃

2020-06-03 20:26 UTC, ashley3 commented
Looks like I accidentally commented on a specific commit instead of the pull request as a whole, whoops. I'm gonna delete those comments and try again :)

2020-06-03 20:29 UTC, ashley3 approved these changes

2020-06-03 20:29 UTC, ashley3 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  ArrayList<String[]> comments = new ArrayList<String[]>();
This can be private :)

2020-06-03 20:29 UTC, ashley3 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    String[] commentComplete = {commenter, comment};
completeComment might be easier to read here

2020-06-03 20:29 UTC, ashley3 commented on portfolio/src/main/webapp/script.js
> +  console.log(comments);
can delete console.log here and below

2020-06-03 23:04 UTC, alexcn3 commented
I can't do a merge unfortunately until you approve my request, Ying. I think it's because changes were requested so the process is different.

2020-06-04 02:22 UTC, eyh8 approved these changes

2020-06-04 03:06 UTC, merged